Atizaz abid
tahirawan4/Martium pull request #2
Opened 2017-09-07 22:30 UTC by aitzazabid

Added the models and dash board and get categories api

2017-09-10 16:13 UTC, tahirawan4 commented on models.py
> +    isRemove = models.BooleanField(default=False)
Always use small letters with `_`. Variable name must be `is_remove`

2017-09-10 16:13 UTC, tahirawan4 commented on models.py
> +    isRemove = models.BooleanField(default=False)
Same as above

2017-09-10 16:14 UTC, tahirawan4 commented on models.py
> +        verbose_name_plural = 'Authors'
We don't need these meta variables, as author plural is authors by default. Remove it please

2017-09-10 16:14 UTC, tahirawan4 commented on models.py
> +    class Meta:
We won't need here too.

2017-09-10 16:14 UTC, tahirawan4 commented on models.py
> +    isRemove = models.BooleanField(default=False)
Update this one.

2017-09-10 16:15 UTC, tahirawan4 commented on models.py
> +    isRemove = models.BooleanField(default=False)
Update it

2017-09-10 16:15 UTC, tahirawan4 commented on models.py
> +    isRemove = models.BooleanField(default=False)
Update it

2017-09-10 16:15 UTC, tahirawan4 commented on models.py
> +        verbose_name_plural = "Pages"
We won't need this.

2017-09-10 16:16 UTC, tahirawan4 commented on models.py
> +        verbose_name_plural = 'Galleries'
This is good.

2017-09-10 16:16 UTC, tahirawan4 commented on models.py
> +    isRemove = models.BooleanField(default=False)
Update it.

2017-09-10 16:16 UTC, tahirawan4 commented on models.py
> +        verbose_name_plural = 'Visitors'
Remove it.

2017-09-10 16:16 UTC, tahirawan4 commented on parser/constants.py
> +
Update all constants with all capitals.

2017-09-10 16:17 UTC, tahirawan4 commented on parser/models.py
> +from django.db import models
Why we have two models files here?
Please remove one and update all the migrations.

2017-09-10 16:18 UTC, tahirawan4 commented on parser/views.py
> +    # TODO: This view is call from the url and will return the Feedly fetch records to html view
Why a lot of line breaks here??

2017-09-10 16:21 UTC, tahirawan4 requested changes
Please remove all `.`  files committed in the repo.

2017-09-11 16:37 UTC, aitzazabid commented
ok
thanks for the review
i will update ,but let me know these model are enough for the v1

On Sun, Sep 10, 2017 at 9:21 PM, Tahir Fazal <notifications@github.com>
wrote:

> *@tahirawan4* requested changes on this pull request.
>
> Please remove all . files committed in the repo.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/tahirawan4/Martium/pull/2#pullrequestreview-61688613>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AOHSqYSxNVIueYYUb-6eq4el3G8DtiSGks5shAx8gaJpZM4PQeMA>
> .
>

2017-09-11 18:07 UTC, tahirawan4 commented
@aitzazabid @AhmedKakar 
Please resolve conflicts by merging master into this branch,
How to do that.
1) Change your branch to master
2) Pull master
3) Switch Back to this branch
4) And now merge master in this branch

Also models and not good for V1, I need to update the, too. I am exploring feedly. As soon as i got something i will update it.

2017-09-11 21:10 UTC, tahirawan4 commented
Where are the migrations??? Did you try to run this code?? @aitzazabid @AhmedKakar

2017-09-11 21:12 UTC, tahirawan4 commented on parser/models.py
> +    description = RedactorField()
@aitzazabid  @AhmedKakar  What is this field? How do you import this field??

2017-09-11 21:12 UTC, tahirawan4 commented on parser/models.py
> +    description = RedactorField()
Same here?

2017-09-11 21:14 UTC, tahirawan4 commented
@aitzazabid @AhmedKakar As you are using requests in views, When ever you use a third party module, please add it into requirements file.

2017-09-12 09:14 UTC, aitzazabid commented
ok
we didn't run the migration yet ,waiting for the best and approved models

On Tue, Sep 12, 2017 at 2:15 AM, Tahir Fazal <notifications@github.com>
wrote:

> Reopened #2 <https://github.com/tahirawan4/Martium/pull/2>.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/tahirawan4/Martium/pull/2#event-1244134580>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AOHSqaCRhCOmuJ3kJ3f_gWt7MMseOeO4ks5shaLlgaJpZM4PQeMA>
> .
>

2017-09-14 07:43 UTC, tahirawan4 approved these changes

2017-09-14 07:43 UTC, merged